/*import 'package:flutter/material.dart';

import 'doctorClass.dart';
import 'patientClass.dart';

 DummyDataOfDoctor= [

Doctor(
  id: '1',
  name: "Amany ali fekey",
  image: "https://aawafi.com/uploads/partners/profile/doctor.jpg",
  user: "user",
  department: "Pediatrician",
  acessed_taskesg: [
    "task1Id",
    "task2Id",
    "task3Id",
    "task4Id",
  ]
  ),
Doctor(
  id: '2',
  name: "Heba ali fekey",
  image: "https://t4.ftcdn.net/jpg/02/60/04/09/360_F_260040900_oO6YW1sHTnKxby4GcjCvtypUCWjnQRg5.jpg",
  user: "user",
  department: "Pediatrician",
  acessed_taskesg: [
    "task1Id",
    "task2Id",
    "task3Id",
    "task4Id",
  ]
  ),Doctor(
  id: '3',
  name: "Tasnem ali fekey",
  image: "https://aawafi.com/uploads/partners/profile/doctor.jpg",
  user: "user",
  department: "Pediatrician",
  acessed_taskesg: [
    "task1Id",
    "task2Id",
    "task3Id",
    "task4Id",
  ]
  ),
];
 DummyDataOfPatient =  [
  Patient(
    id: "1",
    name: "Hana Ali Ahmed",
    image: "assets/images/11.jpg",
    check_in: "1/2/2020",
    check_out: "5/8/2021",
    gender: "femele",
    age :"25" ,
    mobel: "0101156655" ,
    nationality: "Fracne",
    user:"user",
    stay_room: "3D",
    acessed_tasks: [
    "task1Id",
    "task2Id",
    "task3Id",
    "task4Id",],
    doctorId: "1"
    ),
     Patient(
    id: "2",
    name: "Mohamed Ali Ahmed",
    image: "assets/images/1.jpg",
    check_in: "1/2/2020",
    check_out: "5/8/2021",
    gender: "male",
    age :"30" ,
    mobel: "0101156655" ,
    nationality: "Fracne",
    user:"user",
    stay_room: "4D",
    acessed_tasks: [
    "task1Id",
    "task2Id",
    "task3Id",
    "task4Id",
    ],doctorId: "1"),
     Patient(
    id: "3",
    name: "Ahmed Ali Ahmed",
    image: "assets/images/2.jpg",
    check_in: "1/2/2020",
    check_out: "5/8/2021",
    gender: "male",
    age :"25" ,
    mobel: "0101156655" ,
    nationality: "Fracne",
    user:"user",
    stay_room: "5D",
    acessed_tasks: [
    "task1Id",
    "task2Id",
    "task3Id",
    "task4Id",
    ],
    doctorId: "1"),
Patient(
    id: "4",
    name: "Hana Ali Ahmed",
    image: "assets/images/11.jpg",
    check_in: "1/2/2020",
    check_out: "5/8/2021",
    gender: "femele",
    age :"25" ,
    mobel: "0101156655" ,
    nationality: "Fracne",
    user:"user",
    stay_room: "3D",
    acessed_tasks: [
    "task1Id",
    "task2Id",
    "task3Id",
    "task4Id",
    ],
    doctorId: "2"),
     Patient(
    id: "5",
    name: "Mohamed Ali Ahmed",
image: "assets/images/1.jpg",
    check_in: "1/2/2020",
    check_out: "5/8/2021",
    gender: "male",
    age :"30" ,
    mobel: "0101156655" ,
    nationality: "Fracne",
    user:"user",
    stay_room: "4D",
    acessed_tasks: [
    "task1Id",
    "task2Id",
    "task3Id",
    "task4Id",
    ],
    doctorId: "2"),
     Patient(
    id: "6",
    name: "Ahmed Ali Ahmed",
    image: "assets/images/2.jpg",
    check_in: "1/2/2020",
    check_out: "5/8/2021",
    gender: "male",
    age :"25" ,
    mobel: "0101156655" ,
    nationality: "Fracne",
    user:"user",
    stay_room: "5D",
    acessed_tasks: [
    "task1Id",
    "task2Id",
    "task3Id",
    "task4Id",
    ],
    doctorId: "2"),


    Patient(
    id: "7",
    name: "Hana Ali Ahmed",
    image: "assets/images/11.jpg",
    check_in: "1/2/2020",
    check_out: "5/8/2021",
    gender: "femele",
    age :"25" ,
    mobel: "0101156655" ,
    nationality: "Fracne",
    user:"user",
    stay_room: "3D",
    acessed_tasks: [
    "task1Id",
    "task2Id",
    "task3Id",
    "task4Id",],
    doctorId: "3"
    ),
     Patient(
    id: "8",
    name: "Mohamed Ali Ahmed",
image: "assets/images/3.jpg",
    check_in: "1/2/2020",
    check_out: "5/8/2021",
    gender: "male",
    age :"30" ,
    mobel: "0101156655" ,
    nationality: "Fracne",
    user:"user",
    stay_room: "4D",
    acessed_tasks: [
    "task1Id",
    "task2Id",
    "task3Id",
    "task4Id",
    ],doctorId: "3"),
     Patient(
    id: "9",
    name: "Ahmed Ali Ahmed",
    image: "assets/images/2.jpg",
    check_in: "1/2/2020",
    check_out: "5/8/2021",
    gender: "male",
    age :"25" ,
    mobel: "0101156655" ,
    nationality: "Fracne",
    user:"user",
    stay_room: "5D",
    acessed_tasks: [
    "task1Id",
    "task2Id",
    "task3Id",
    "task4Id",
    ],
    doctorId: "3"),
Patient(
    id: "10",
    name: "Hana Ali Ahmed",
    image: "assets/images/11.jpg",
    check_in: "1/2/2020",
    check_out: "5/8/2021",
    gender: "femele",
    age :"25" ,
    mobel: "0101156655" ,
    nationality: "Fracne",
    user:"user",
    stay_room: "3D",
    acessed_tasks: [
    "task1Id",
    "task2Id",
    "task3Id",
    "task4Id",
    ],
    doctorId: "3"),
     Patient(
    id: "11",
    name: "Mohamed Ali Ahmed",
image: "assets/images/3.jpg",
    check_in: "1/2/2020",
    check_out: "5/8/2021",
    gender: "male",
    age :"30" ,
    mobel: "0101156655" ,
    nationality: "Fracne",
    user:"user",
    stay_room: "4D",
    acessed_tasks: [
    "task1Id",
    "task2Id",
    "task3Id",
    "task4Id",
    ],
    doctorId: "3"),
     Patient(
    id: "12",
    name: "Ahmed Ali Ahmed",
image: "assets/images/2.jpg",
    check_in: "1/2/2020",
    check_out: "5/8/2021",
    gender: "male",
    age :"25" ,
    mobel: "0101156655" ,
    nationality: "Fracne",
    user:"user",
    stay_room: "5D",
    acessed_tasks: [
    "task1Id",
    "task2Id",
    "task3Id",
    "task4Id",
    ],
    doctorId: "3"),

     Patient(
    id: "13",
    name: "Ahmed Ali Ahmed",
image: "assets/images/2.jpg",
    check_in: "1/2/2020",
    check_out: "5/8/2021",
    gender: "male",
    age :"25" ,
    mobel: "0101156655" ,
    nationality: "Fracne",
    user:"user",
    stay_room: "5D",
    acessed_tasks: [
    "task1Id",
    "task2Id",
    "task3Id",
    "task4Id",
    ],
    doctorId: "1"),
Patient(
    id: "14",
    name: "Hana Ali Ahmed",
image: "assets/images/1.jpg",
    check_in: "1/2/2020",
    check_out: "5/8/2021",
    gender: "femele",
    age :"25" ,
    mobel: "0101156655" ,
    nationality: "Fracne",
    user:"user",
    stay_room: "3D",
    acessed_tasks: [
    "task1Id",
    "task2Id",
    "task3Id",
    "task4Id",
    ],
    doctorId: "1"),
     Patient(
    id: "15",
    name: "Mohamed Ali Ahmed",
image: "assets/images/3.jpg",
    check_in: "1/2/2020",
    check_out: "5/8/2021",
    gender: "male",
    age :"30" ,
    mobel: "0101156655" ,
    nationality: "Fracne",
    user:"user",
    stay_room: "4D",
    acessed_tasks: [
    "task1Id",
    "task2Id",
    "task3Id",
    "task4Id",
    ],
    doctorId: "2"),
     Patient(
    id: "16",
    name: "Ahmed Ali Ahmed",
    image: "assets/images/2.jpg",
    check_in: "1/2/2020",
    check_out: "5/8/2021",
    gender: "male",
    age :"25" ,
    mobel: "0101156655" ,
    nationality: "Fracne",
    user:"user",
    stay_room: "5D",
    acessed_tasks: [
    "task1Id",
    "task2Id",
    "task3Id",
    "task4Id",
    ],
    doctorId: "3"),
];*/